version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - NEXTAUTH_URL=${NEXTAUTH_URL}
  #     - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
  #     - OIDC_ISSUER=${OIDC_ISSUER}
  #     - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
  #     - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
  #     - WEBHOOK_SECRET=${WEBHOOK_SECRET}
  #   depends_on:
  #     - db

  db:
    image: postgres:15-alpine
    ports:
      - "5221:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dandelion
    volumes:
      - dandelion_db_data:/var/lib/postgresql/data

volumes:
  dandelion_db_data: